ScrollReveal().reveal('.animate-trailer', {delay: 200, reset: false, duration: 1000, distance: '50px', origin: 'bottom'})
ScrollReveal().reveal('.animate-bottom', {delay: 375, reset: false, duration: 1000, distance: '50px', origin: 'bottom'})
ScrollReveal().reveal('.animate-bottom-fast', {delay: 70, reset: false, duration: 1000, distance: '50px', origin: 'bottom'})
ScrollReveal().reveal('.animate-right', {delay: 375, reset: false, duration: 1000, distance: '50px', origin: 'right'})
ScrollReveal().reveal('.animate-left', {delay: 375, reset: false, duration: 1000, distance: '50px', origin: 'left'})